# Generated by Django 5.2.1 on 2025-07-07 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='ean',
            field=models.CharField(blank=True, max_length=100, verbose_name='PLU/EAN'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observações do Almoxarife'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('NEGADO', 'Negado'), ('SUBSTITUIDO', 'Substituído')], default='PENDENTE', max_length=20, verbose_name='Status do Item'),
        ),
        migrations.AlterField(
            model_name='request',
            name='observations',
            field=models.TextField(blank=True, max_length=255, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='category',
            field=models.CharField(choices=[('INSUMO_PRODUCAO', 'Insumo (Produção)'), ('EMBALAGENS', 'Embalagens'), ('LIMPEZA', 'Limpeza'), ('AREA_DE_VENDA', 'Área de Venda'), ('ADMINISTRATIVO', 'Administrativo')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GESTOR', 'Gestor'), ('ENCARREGADO', 'Encarregado'), ('ALMOXARIFE', 'Almoxarife')], default='ENCARREGADO', max_length=20, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='SubstitutedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, verbose_name='Nome do Item de Substituição')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade Fornecida')),
                ('ean', models.CharField(blank=True, max_length=100, verbose_name='PLU/EAN do Substituto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='substitution', to='core.requestitem', verbose_name='Item Original')),
            ],
            options={
                'verbose_name': 'Item Substituído',
                'verbose_name_plural': 'Itens Substituídos',
            },
        ),
    ]
