# Generated by Django 5.2.1 on 2025-07-09 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_requestitem_ean_requestitem_observations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='status',
        ),
        migrations.AddField(
            model_name='request',
            name='atendido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_attended', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por'),
        ),
        migrations.AlterField(
            model_name='request',
            name='observations',
            field=models.TextField(max_length=255, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('APPROVED', 'Aprovada')], default='PENDING', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='category',
            field=models.CharField(choices=[('INSUMO_PRODUCAO', 'Insumo(Produção)'), ('EMBALAGENS', 'Embalagens'), ('LIMPEZA', 'Limpeza'), ('AREA_DE_VENDA', 'Area de venda'), ('ADIMINISTRATIVO', 'Administrativo')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Gestor', 'Gestor'), ('Encarregado', 'Encarregado'), ('Almoxarife', 'Almoxarife')], default='Almoxarife', max_length=20, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector'),
        ),
        migrations.DeleteModel(
            name='SubstitutedItem',
        ),
    ]
