# Generated by Django 5.2.1 on 2025-07-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_requestitem_ean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='observacao_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação do Item'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='quantidade_atendida',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade Atendida'),
        ),
    ]
