# Generated by Django 5.2.4 on 2025-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requestitem_observacao_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('APPROVED', 'Atendida')], default='PENDING', max_length=15, verbose_name='Status'),
        ),
    ]
