services:
  - type: web
    name: requisita-facil-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      python manage.py makemigrations &&
      python manage.py migrate &&
      waitress-serve --bind=0.0.0.0:10000 requisita_facil.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: requisita_facil.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
    plan: free
    autoDeploy: true
    region: oregon 