services:
  - type: web
    name: requisita-facil-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn requisita_facil.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: requisita_facil.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    plan: free
    autoDeploy: true
    region: oregon 