services:
  - type: web
    name: requisita-facil-web
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn requisita_facil.wsgi:application --bind 0.0.0.0:$PORT"
    plan: free
    autoDeploy: true
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: requisita-facil-web.onrender.com
