services:
  - type: web
    name: requisita-facil-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py makemigrations && python manage.py migrate && gunicorn requisita_facil.wsgi:application --bind 0.0.0.0:10000"
    plan: free
    autoDeploy: true
    region: oregon
